"""Render a newsletter (our markdown format) into a MediaPulse HTML email + plain text.

The HTML comes from a tokenized template generated by the `email-playground` React Email
project (`npm run build:templates` writes `src/templates/newsletter.html`). This module only
parses the markdown and fills the template's `{{tokens}}` and `<!--#region-->` blocks, so the
visual design lives in React, not here. The template is a build artifact and is gitignored, so
it must be generated before this module can render (CI and the Docker build do this; locally run
`npm run build:templates` inside `email-playground/`).
"""

import html as _html
import re
from functools import lru_cache
from pathlib import Path

_TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "templates" / "newsletter.html"

_QUICK_HITS = "Quick Hits"

_TITLE = re.compile(r"(?m)^#\s+(.+)$")
_READ = re.compile(r"\[Read:\s*([^\]]*)\]\(([^)\s]+)\)")
_INLINE = re.compile(r"\[([^\]]+)\]\((https?://[^)\s]+)\)")

_LINK = "color:#2563eb;text-decoration:underline;"


def _inline(text: str) -> str:
    """Escape text and turn inline `[label](https://…)` into anchors; newlines to <br>."""
    out: list[str] = []
    last = 0
    for match in _INLINE.finditer(text):
        out.append(_html.escape(text[last : match.start()]))
        label = _html.escape(match.group(1))
        url = _html.escape(match.group(2), quote=True)
        out.append(f'<a href="{url}" style="{_LINK}">{label}</a>')
        last = match.end()
    out.append(_html.escape(text[last:]))

    return "".join(out).replace("\n", "<br>")


def _parse(markdown: str) -> tuple[str, str, list[tuple[str, list[dict]]]]:
    title_match = _TITLE.search(markdown)
    title = title_match.group(1).strip() if title_match else "Newsletter"
    body = markdown[title_match.end() :] if title_match else markdown

    parts = re.split(r"(?m)^##\s+(.+)$", body)
    summary = parts[0].strip()

    sections: list[tuple[str, list[dict]]] = []
    for index in range(1, len(parts), 2):
        name = parts[index].strip()
        content = parts[index + 1] if index + 1 < len(parts) else ""
        items: list[dict] = []
        for block in re.split(r"(?m)^\s*---\s*$", content):
            link = _READ.search(block)
            if not link:
                continue
            text = re.sub(r"\n{2,}", "\n", _READ.sub("", block)).strip()
            items.append({"summary": text, "title": link.group(1).strip(), "url": link.group(2).strip()})
        sections.append((name, items))

    return title, summary, sections


@lru_cache(maxsize=1)
def _template() -> str:
    """Load the tokenized HTML template generated by email-playground."""
    try:
        return _TEMPLATE_PATH.read_text(encoding="utf-8")
    except FileNotFoundError as error:
        raise FileNotFoundError(
            f"Newsletter template not found at {_TEMPLATE_PATH}. Generate it by running "
            "`npm install && npm run build:template` inside the email-playground directory."
        ) from error


def _region(template: str, name: str) -> tuple[str, str]:
    """Return ``(block, inner)`` for a ``<!--#name-->…<!--/name-->`` region.

    ``block`` includes the markers (for removal or substitution); ``inner`` is the content
    between them.
    """
    start = f"<!--#{name}-->"
    end = f"<!--/{name}-->"
    start_index = template.index(start)
    inner_start = start_index + len(start)
    inner_end = template.index(end, inner_start)
    block = template[start_index : inner_end + len(end)]

    return block, template[inner_start:inner_end]


def _render_item(item_inner: str, item: dict, *, is_first: bool) -> str:
    """Fill one item template with a parsed item, handling the optional itemsep/readlink regions."""
    rendered = item_inner

    itemsep_block, itemsep_inner = _region(rendered, "itemsep")
    rendered = rendered.replace(itemsep_block, "" if is_first else itemsep_inner)

    readlink_block, readlink_inner = _region(rendered, "readlink")
    if item["url"]:
        cta = _html.escape(item["title"] or "the source")
        url = _html.escape(item["url"], quote=True)
        filled = readlink_inner.replace("{{item_url}}", url).replace("{{item_title}}", cta)
        rendered = rendered.replace(readlink_block, filled)
    else:
        rendered = rendered.replace(readlink_block, "")

    return rendered.replace("{{item_summary}}", _inline(item["summary"]))


def _render_section(section_template: str, name: str, items: list[dict], *, is_first: bool) -> str:
    """Fill one section template (standard or quick-hits) with its name and items."""
    item_block, item_inner = _region(section_template, "item")
    items_html = "".join(_render_item(item_inner, item, is_first=position == 0) for position, item in enumerate(items))
    rendered = section_template.replace(item_block, items_html)

    sectionsep_block, sectionsep_inner = _region(rendered, "sectionsep")
    rendered = rendered.replace(sectionsep_block, "" if is_first else sectionsep_inner)

    return rendered.replace("{{section_name}}", _html.escape(name))


def _render_html(
    title: str,
    summary: str,
    sections: list[tuple[str, list[dict]]],
    footer_note: str,
    subject_symbol: str | None,
    unsubscribe_url: str | None,
) -> str:
    template = _template()
    sections_block, sections_inner = _region(template, "sections")
    standard_template = _region(sections_inner, "section")[1]
    quickhits_template = _region(sections_inner, "quickhits")[1]
    standfirst_block, standfirst_inner = _region(template, "standfirst")
    unsubscribe_block, unsubscribe_inner = _region(template, "unsubscribe")

    rendered_sections: list[str] = []
    for name, items in sections:
        if not items:
            continue
        section_template = quickhits_template if name == _QUICK_HITS else standard_template
        rendered_sections.append(_render_section(section_template, name, items, is_first=not rendered_sections))

    html = template.replace(sections_block, "".join(rendered_sections))

    if summary:
        html = html.replace(standfirst_block, standfirst_inner.replace("{{summary}}", _inline(summary)))
    else:
        html = html.replace(standfirst_block, "")

    if unsubscribe_url:
        url = _html.escape(unsubscribe_url, quote=True)
        label = _html.escape(subject_symbol or "these")
        filled = unsubscribe_inner.replace("{{unsubscribe_url}}", url).replace("{{symbol}}", label)
        html = html.replace(unsubscribe_block, filled)
    else:
        html = html.replace(unsubscribe_block, "")

    html = html.replace("{{title}}", _html.escape(title))
    html = html.replace("{{footer_note}}", _html.escape(footer_note))

    return html


def render_newsletter_email(
    markdown: str,
    *,
    subject_symbol: str | None = None,
    unsubscribe_url: str | None = None,
) -> dict[str, str]:
    """Return ``{"subject", "html", "text"}`` for the newsletter markdown."""
    title, summary, sections = _parse(markdown)

    subject = (subject_symbol or "").strip()
    footer_note = (
        f"You are receiving this because you subscribed to {subject} updates."
        if subject
        else "You are receiving this because you subscribed to updates."
    )

    html = _render_html(title, summary, sections, footer_note, subject_symbol, unsubscribe_url)

    text_lines = [title, "", summary, ""] if summary else [title, ""]
    for name, items in sections:
        if not items:
            continue
        text_lines.append(name)
        for item in items:
            text_lines.append(item["summary"])
            if item["url"]:
                text_lines.append(f"Read {item['title']}: {item['url']}")
            text_lines.append("---")
        text_lines.append("")
    text_lines.append(footer_note)

    return {"subject": title, "html": html, "text": "\n".join(text_lines).strip()}
